# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19XilEKjSAUEn_UYfVv22swMsqrLpm45n
"""

from google.colab import files

uploaded = files.upload()



import pandas as pd
import streamlit as st
import seaborn as sns
import matplotlib.pyplot as plt


df = pd.read_excel("Application Database.xlsx", sheet_name="Applications")
df.head()

# Streamlit UI
st.title("Startup Q&A Chatbot")

query = st.text_input("Ask a question about a startup:")

if query:
    response = "Sorry, I don't have an answer for that."

    if "what does" in query.lower():
        startup = query.split(" ")[2]
        result = df[df["Startup name"].str.lower() == startup.lower()]
        if not result.empty:
            response = result.iloc[0]["What is your company going to make? Please describe your product and what it does or will do."]

    elif "founders of" in query.lower():
        startup = query.split(" ")[-1]
        result = df[df["Startup name"].str.lower() == startup.lower()]
        if not result.empty:
            response = result.iloc[0]["Founder Names"]

    elif "chart of founders" in query.lower():
        st.write("### Founders per Startup")
        plt.figure(figsize=(10, 5))
        sns.histplot(df["Founders #"], bins=10)
        st.pyplot(plt)
        response = "Here is a visualization of the number of founders per startup."

    st.write(response)
